-- AlterEnum
ALTER TYPE "FeeStatus" ADD VALUE 'PROCESSING';

-- AlterTable
ALTER TABLE "inspection_fees" ADD COLUMN     "attempts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "idempotencyKey" TEXT;

-- AlterTable
ALTER TABLE "properties" ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "ownerClientName" SET DATA TYPE TEXT,
ALTER COLUMN "province" SET DATA TYPE TEXT,
ALTER COLUMN "district" SET DATA TYPE TEXT,
ALTER COLUMN "sector" SET DATA TYPE TEXT,
ALTER COLUMN "cell" SET DATA TYPE TEXT,
ALTER COLUMN "villageStreet" SET DATA TYPE TEXT;
