/** Stable machine-readable codes. Clients switch on these, never on prose. */
export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',

  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_PASSWORD_POLICY: 'AUTH_PASSWORD_POLICY',

  USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
  BRANCH_CODE_EXISTS: 'BRANCH_CODE_EXISTS',

  INSPECTION_NOT_FOUND: 'INSPECTION_NOT_FOUND',
  INSPECTION_INVALID_TRANSITION: 'INSPECTION_INVALID_TRANSITION',
  INSPECTION_INCOMPLETE: 'INSPECTION_INCOMPLETE',
  INSPECTION_STALE_VERSION: 'INSPECTION_STALE_VERSION',

  PHOTO_INVALID_TYPE: 'PHOTO_INVALID_TYPE',
  PHOTO_TOO_LARGE: 'PHOTO_TOO_LARGE',

  REPORT_NOT_READY: 'REPORT_NOT_READY',
  STORAGE_FAILURE: 'STORAGE_FAILURE',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
