import { FieldType, PhotoCategory } from '@prisma/client';
export interface VisibilityRule { field?: string; equals?: unknown; min?: number; max?: number; all?: VisibilityRule[]; any?: VisibilityRule[]; }
export interface FieldValidation { min?: number; max?: number; minLength?: number; maxLength?: number; pattern?: string; visibleWhen?: VisibilityRule; }
export interface FieldDefinition { id:string; code:string; label:string; type:FieldType; required:boolean; validation?:FieldValidation|null; }
export interface SectionDefinition { code:string; name:string; isAssessment:boolean; fields:FieldDefinition[]; }
export interface PhotoRuleDefinition { category:PhotoCategory; minCount:number; required:boolean; }
export interface SubmittedValue { fieldId:string; valueText?:string|null; valueNumber?:number|null; valueDate?:Date|null; valueBool?:boolean|null; valueJson?:unknown; }
export interface AssessmentState { categoryCode:string; categoryName:string; rating:number|null; condition:string|null; }
export interface CompletenessInput { sections:SectionDefinition[]; photoRules:PhotoRuleDefinition[]; values:SubmittedValue[]; fieldCodesById?:Record<string,string>; assessments:AssessmentState[]; photoCountsByCategory:Record<string,number>; hasOwner:boolean; hasValuation:boolean; hasLocation:boolean; }
export interface CompletenessIssue { code:string; sectionCode?:string; fieldCode?:string; message:string; blocking:boolean; }
export interface CompletenessResult { complete:boolean; percentage:number; issues:CompletenessIssue[]; blockingIssues:CompletenessIssue[]; }
function hasValue(v:SubmittedValue|undefined):boolean { if(!v)return false; if(typeof v.valueText==='string'&&v.valueText.trim()!=='')return true; if(v.valueNumber!==undefined&&v.valueNumber!==null)return true; if(v.valueDate!==undefined&&v.valueDate!==null)return true; if(v.valueBool!==undefined&&v.valueBool!==null)return true; if(v.valueJson!==undefined&&v.valueJson!==null)return Array.isArray(v.valueJson)?v.valueJson.length>0:true; return false; }
function rawValue(v:SubmittedValue|undefined):unknown { if(!v)return undefined; if(v.valueText!=null)return v.valueText; if(v.valueNumber!=null)return v.valueNumber; if(v.valueBool!=null)return v.valueBool; if(v.valueDate!=null)return v.valueDate; return v.valueJson; }
function sameValue(a:unknown,e:unknown):boolean { if(Array.isArray(a))return a.map(String).includes(String(e)); return String(a??'').toUpperCase()===String(e??'').toUpperCase(); }
function matchesRule(r:VisibilityRule|undefined,values:Map<string,unknown>):boolean { if(!r)return true; if(r.all&&!r.all.every(x=>matchesRule(x,values)))return false; if(r.any&&!r.any.some(x=>matchesRule(x,values)))return false; if(r.field){const a=values.get(r.field);if(r.equals!==undefined&&!sameValue(a,r.equals))return false;if(r.min!==undefined&&(typeof a!=='number'||a<r.min))return false;if(r.max!==undefined&&(typeof a!=='number'||a>r.max))return false;} return true; }
function validateFieldValue(f:FieldDefinition,v:SubmittedValue,sectionCode:string):CompletenessIssue[]{const out:CompletenessIssue[]=[];const r=f.validation;if(!r)return out;if(typeof v.valueNumber==='number'){if(r.min!==undefined&&v.valueNumber<r.min)out.push({code:'VALUE_BELOW_MIN',sectionCode,fieldCode:f.code,message:`${f.label} must be at least ${r.min}.`,blocking:true});if(r.max!==undefined&&v.valueNumber>r.max)out.push({code:'VALUE_ABOVE_MAX',sectionCode,fieldCode:f.code,message:`${f.label} must be no more than ${r.max}.`,blocking:true});}const t=v.valueText;if(typeof t==='string'&&t.length){if(r.minLength!==undefined&&t.length<r.minLength)out.push({code:'TEXT_TOO_SHORT',sectionCode,fieldCode:f.code,message:`${f.label} must be at least ${r.minLength} characters.`,blocking:true});if(r.maxLength!==undefined&&t.length>r.maxLength)out.push({code:'TEXT_TOO_LONG',sectionCode,fieldCode:f.code,message:`${f.label} must be no more than ${r.maxLength} characters.`,blocking:true});if(r.pattern){let ok=true;try{ok=new RegExp(r.pattern).test(t);}catch{}if(!ok)out.push({code:'PATTERN_MISMATCH',sectionCode,fieldCode:f.code,message:`${f.label} is not in the expected format.`,blocking:true});}}return out;}
export function evaluateCompleteness(input:CompletenessInput):CompletenessResult { const issues:CompletenessIssue[]=[];const byId=new Map(input.values.map(v=>[v.fieldId,v]));const byCode=new Map<string,unknown>();for(const s of input.sections)for(const f of s.fields){const v=byId.get(f.id);if(v)byCode.set(f.code,rawValue(v));}for(const [id,v] of byId){const code=input.fieldCodesById?.[id];if(code)byCode.set(code,rawValue(v));}let satisfied=0,total=0;for(const s of input.sections)for(const f of s.fields){if(!matchesRule(f.validation?.visibleWhen,byCode))continue;const v=byId.get(f.id);if(f.required){total++;if(hasValue(v))satisfied++;else issues.push({code:'REQUIRED_FIELD_MISSING',sectionCode:s.code,fieldCode:f.code,message:`${f.label} is required.`,blocking:true});}if(v&&hasValue(v))issues.push(...validateFieldValue(f,v,s.code));}
for(const a of input.assessments){total++;if(a.rating!=null)satisfied++;else issues.push({code:'ASSESSMENT_NOT_RATED',sectionCode:a.categoryCode,message:`${a.categoryName} has not been rated.`,blocking:true});}
for(const r of input.photoRules){if(!r.required)continue;total++;const count=input.photoCountsByCategory[r.category]??0;if(count>=r.minCount)satisfied++;else issues.push({code:'PHOTO_REQUIREMENT_UNMET',sectionCode:'PHOTOS',message:`${describePhotoCategory(r.category)} requires ${r.minCount} photograph(s); ${count} provided.`,blocking:true});}
total++;if(input.hasOwner)satisfied++;else issues.push({code:'OWNER_MISSING',sectionCode:'OWNER',message:'Owner information has not been recorded.',blocking:true});
const structuredValuation=hasValue(byId.get(input.sections.flatMap(s=>s.fields).find(f=>f.code==='LAND_ESTIMATED_VALUE')?.id??''))||hasValue(byId.get(input.sections.flatMap(s=>s.fields).find(f=>f.code==='IMPROVED_TOTAL_VALUE')?.id??''));
total++;if(input.hasValuation||structuredValuation)satisfied++;else issues.push({code:'VALUATION_MISSING',sectionCode:'VALUATION',message:'Valuation has not been recorded.',blocking:true});
total++;if(input.hasLocation)satisfied++;else issues.push({code:'LOCATION_MISSING',sectionCode:'LOCATION',message:'GPS location has not been captured at the property.',blocking:true});const blockingIssues=issues.filter(i=>i.blocking);return{complete:blockingIssues.length===0,percentage:total===0?100:Math.round(satisfied/total*100),issues,blockingIssues}; }
export function describePhotoCategory(category:PhotoCategory|string):string {const labels:Record<string,string>={FRONT_VIEW:'Front view',REAR_VIEW:'Rear view',LEFT_SIDE:'Left side',RIGHT_SIDE:'Right side',INTERIOR:'Interior',ROOF:'Roof',FOUNDATION:'Foundation',ROAD_ACCESS:'Road access',UTILITIES:'Utilities',SURROUNDINGS:'Surroundings',DOCUMENT:'Document',OTHER:'Other'};return labels[category]??String(category);}
